# Generated by Django 6.0.5 on 2026-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.FileField(blank=True, upload_to='properties/main/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(blank=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
