# Generated by Django 6.0.5 on 2026-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_main_image_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='properties/documents/'),
        ),
    ]
