# Generated by Django 6.0.5 on 2026-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_verification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
