# Generated by Django 6.0.5 on 2026-05-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
