# Generated by Django 6.0.5 on 2026-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_new_user_registrations', models.BooleanField(default=True)),
                ('enable_listing_submissions', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('auto_approve_verified_owners', models.BooleanField(default=False)),
                ('require_document_upload', models.BooleanField(default=True)),
                ('enable_fair_price_indicator', models.BooleanField(default=True)),
                ('show_view_counts_publicly', models.BooleanField(default=True)),
                ('rental_coverage', models.CharField(choices=[('ekiti', 'Ekiti State only'), ('ekiti_ondo', 'Ekiti + Ondo'), ('south_west', 'All South-West states'), ('nationwide', 'Nationwide')], default='ekiti', max_length=20)),
                ('buy_land_coverage', models.CharField(choices=[('nationwide', 'Nationwide (all 36 states + FCT)'), ('selected', 'Selected states only')], default='nationwide', max_length=20)),
            ],
            options={
                'verbose_name': 'platform setting',
                'verbose_name_plural': 'platform settings',
            },
        ),
    ]
