# Generated by Django 6.0.5 on 2026-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_platformsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsetting',
            name='require_document_upload',
            field=models.BooleanField(default=False),
        ),
    ]
