# Generated by Django 6.0.5 on 2026-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('flagged', 'Flagged'), ('sold', 'Sold'), ('rented', 'Rented')], default='draft', max_length=20),
        ),
    ]
