# Generated by Django 6.0.5 on 2026-05-15 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='evidence_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='investigation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='owner_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_listing_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
